version: 2.1

executors:
  go_image:
    docker:
      - image: cimg/go:1.13
  dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1

jobs:
  test:
    executor: dotnet
    steps:
      - checkout
      - run:
          name: Install Java for SonarCloud Scanner
          command: |
            apt update -y
            apt install default-jdk -y
            apt install nodejs -y
      - run:
          name: Run SonarCloud Scanner
          command: |
            export PATH="$PATH:/root/.dotnet/tools"
            dotnet tool install --global dotnet-sonarscanner --version 4.10.0
            dotnet restore
            dotnet-sonarscanner begin /k:"Gaardsholt_$CIRCLE_PROJECT_REPONAME" /n:"$CIRCLE_PROJECT_REPONAME" /o:"gaardsholt-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$SONAR"
            dotnet msbuild /t:Rebuild
            dotnet-sonarscanner end /d:sonar.login="$SONAR"
  build:
    executor: go_image
    steps:
        - checkout
        - setup_remote_docker
        - run: |
            docker build -t busylight-server:1 .
  build-n-push:
    executor: go_image
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker login --username $DOCKER_USER --password $DOCKER_PASS
          docker build -t gaardsholt/$CIRCLE_PROJECT_REPONAME:${CIRCLE_TAG} -t gaardsholt/$CIRCLE_PROJECT_REPONAME:latest .
          docker push gaardsholt/$CIRCLE_PROJECT_REPONAME:${CIRCLE_TAG}
          docker push gaardsholt/$CIRCLE_PROJECT_REPONAME:latest
  cleanup:
    executor: go_image
    steps:
      - run:
          name: gcloud login
          command: |
            echo "Will now do some cleanup"

workflows:
  build:
    jobs:
      - test:
          context: gaardsholt
      - build:
          context: gaardsholt
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /^[0-9]+(\.[0-9]+)*(-.*)*$/
  build-n-push:
    jobs:
      - build-n-push:
          context: gaardsholt
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/