version: 2.1

executors:
  go_image:
    docker:
      - image: cimg/go:1.13


jobs:
  build:
    executor: go_image
    steps:
        - checkout
        - setup_remote_docker
        - run: |
            docker build -t busylight-server:1 .
  build-n-push:
    executor: go_image
    steps:
        - checkout
        - setup_remote_docker
        - run: |
            docker login --username $DOCKER_USER --password $DOCKER_PASS
            docker build -t gaardsholt/$CIRCLE_PROJECT_REPONAME:${CIRCLE_TAG:1} -t gaardsholt/$CIRCLE_PROJECT_REPONAME:latest .
            docker push gaardsholt/$CIRCLE_PROJECT_REPONAME:${CIRCLE_TAG:1}
            docker push gaardsholt/$CIRCLE_PROJECT_REPONAME:latest

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: gaardsholt
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /^[0-9]+(\.[0-9]+)*(-.*)*$/
  build-n-push:
    jobs:
      - build-n-push:
          context: gaardsholt
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/