version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.13
    steps:
        - checkout
        - setup_remote_docker
        - run: |
            docker login --username $DOCKER_USER --password $DOCKER_PASS
            docker build -t busylight-server:1 .
    build-n-push:
      docker:
        - image: cimg/go:1.13
      steps:
          - checkout
          - setup_remote_docker
          - run: |
              docker login --username $DOCKER_USER --password $DOCKER_PASS
              docker build -t busylight-server:1 .
              docker push busylight-server:$CIRCLE_TAG

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^[0-9]+(\.[0-9]+)*(-.*)*$/
  build-n-push:
    jobs:
      - build-n-push:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/